objects/nFORCE__Group__c.object
<CustomObject>
    <description>Generalized grouping object.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <description>--DEPRECATED--

            Moved to Group__c.</description>
        <label>-D Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route_Group__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the group a route is being linked to.</description>
        <inlineHelpText>Choose a group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>nFORCE__Group__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the route a group is being linked to.</description>
        <inlineHelpText>Choose a route.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Route Group</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Route Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/nFORCE__System_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A set of key-value pairs that can be used to set organization-wide parameters</description>
    <label>System Properties</label>
</CustomObject>

classes/csaTestLookupkeyGeneratorInstallerRemote.cls
@isTest(IsParallel=true)
private without sharing class csaTestLookupkeyGeneratorInstallerRemote {

    @isTest
    static void testCheckInstall() {
        nCSA_FRAME.csaTestDataFactory.createForceSystemProperty(
            nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
            csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDKEY,
            csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDVALUE,
            true,
            null
        );

        Map<String, Object> params = new Map<String, Object>();

        Test.startTest();

        Boolean result = (Boolean)nFORCE.RemoteActionController.invoke(
            'csaLookupkeyGeneratorInstallerRemote.CheckInstall', params
        );

        Test.stopTest();

        System.assertEquals(true, result);
    }

    @isTest
    static void testInstall() {
        nFORCE__Group__c testGroup = nCSA_FRAME.csaTestDataFactory.createGroup('admin');
        nFORCE__Route__c testRoute = nCSA_FRAME.csaTestDataFactory.createRoute(
            null, 'testBody', 'csa-admin-dashboard', nCSA_FRAME.csaConstants.ADMINDASHBOARD_ROUTEKEY
        );
        Map<String, Object> params = new Map<String, Object>();

        Test.startTest();

        nFORCE.RemoteActionController.invoke('csaLookupkeyGeneratorInstallerRemote.Install', params);
        List<nFORCE__System_Properties__c> results = [SELECT Id FROM nFORCE__System_Properties__c LIMIT 15];
        List<nFORCE__Route__c> routes = [SELECT Id FROM nFORCE__Route__c LIMIT 15];
        List<nFORCE__Route_Group__c> routeGroups = [SELECT Id FROM nFORCE__Route_Group__c LIMIT 15];

        Test.stopTest();

        System.assertEquals(1, results.size());
        System.assertEquals(2, routes.size());
        System.assertEquals(1, routeGroups.size());
    }

    @isTest
    static void testUninstall() {
        nCSA_FRAME.csaTestDataFactory.createForceSystemProperty(
            nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
            csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDKEY,
            csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDVALUE,
            true,
            null
        );

        Map<String, Object> params = new Map<String, Object>();

        Test.startTest();

        nFORCE.RemoteActionController.invoke('csaLookupkeyGeneratorInstallerRemote.Uninstall', params);
        List<nFORCE__System_Properties__c> results = [SELECT Id FROM nFORCE__System_Properties__c LIMIT 1];

        Test.stopTest();

        System.assertEquals(0, results.size());
    }

    @TestSetup
    private static void testSetup() {
        nFORCE.BeanRegistry.getInstance().registerBean(
            'ClassTypeProvider',
            nFORCE.ClassTypeProvider.class,
            Type.forName('ClassTypeProvider')
        );
    }
}