objects/nFORCE__Group__c.object
<CustomObject>
    <description>Generalized grouping object.</description>
    <fields>
        <fullName>nFORCE__App__c</fullName>
        <description>This field is manually populated. It is required. This field is a unique identifier for the group and is used, in conjunction with a route&apos;s app, to uniquely identify a requested app.</description>
        <inlineHelpText>Enter the group portion of the requested app.

E.g. If the requested app is &apos;loan.change-product&apos;, then the group portion is &apos;loan&apos;.</inlineHelpText>
        <label>App</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__App__c</fullName>
        <description>This field is manually populated. It is required. This field is a unique identifier for the route, and is used, in conjunction with a group&apos;s app, to uniquely identify a requested app.</description>
        <label>App</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>nFORCE__Body__c</fullName>
        <description>This field is required. The admin manually populates this field. This field controls what and how data is displayed in the route. If a screen is being used, a layout type must be set. Otherwise, specific values can be set for Visualforce pages in the system.</description>
        <label>Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <description>--DEPRECATED--

            Moved to Group__c.</description>
        <label>-D Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Navigation__c</fullName>
        <description>This field is required. The admin manually populates this field or it is automatically set via Install Updates. It is the secondary navigation page name for a route.</description>
        <label>Navigation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Order__c</fullName>
        <description>--DEPRECATED--

            Moved to Route_Group__c.Order__c.</description>
        <label>-D Order</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nFORCE__Sub_Navigation__c</fullName>
        <description>This field is manually populated. It is optional. This field is used to determine which subnavigation bar to use for a given route.</description>
        <label>Sub Navigation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Topbar__c</fullName>
        <description>This field is manually populated. It is optional. This field is used to determine which topbar to use for a given route.</description>
        <inlineHelpText>The page include for the top bar region of the base UI template.</inlineHelpText>
        <label>Topbar</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/nFORCE__Route_Group__c.object
<CustomObject>
    <fields>
        <fullName>nFORCE__Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the group a route is being linked to.</description>
        <inlineHelpText>Choose a group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>nFORCE__Group__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Order__c</fullName>
        <description>This field is manually populated. It is required. This field specifies the order a route appears on the left navigation or subnavigation bar.</description>
        <inlineHelpText>The route display order.</inlineHelpText>
        <label>Order</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nFORCE__Parent_Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is manually populated. It is optional. This field specifies the parent route a route is being linked to. If a route has a parent route, it will display in the subnavigation bar for that route. If a parent route is not defined, it will display in the left navigation bar.</description>
        <inlineHelpText>The parent route record for this junction.</inlineHelpText>
        <label>Parent Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Child Route Groups</relationshipLabel>
        <relationshipName>Parent_Route_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__Route__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is manually populated. It is required. This field specifies the route a group is being linked to.</description>
        <inlineHelpText>Choose a route.</inlineHelpText>
        <label>Route</label>
        <referenceTo>nFORCE__Route__c</referenceTo>
        <relationshipLabel>Route Groups</relationshipLabel>
        <relationshipName>Route_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>nFORCE__lookupKey__c</fullName>
        <description>The field is optional. If populated, the value must be unique across all the records of this type. The field typically contains an external identifier that is used to associate the record with its matching record in an external system. The field can also be used to efficiently associate related records when importing data into nCino, without the need to know the internal ID for the record. For more information, refer to https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_nested_object.htm</description>
        <externalId>true</externalId>
        <label>lookupKey</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Route Group</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Route Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/nFORCE__System_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A set of key-value pairs that can be used to set organization-wide parameters</description>
    <fields>
        <fullName>nFORCE__Category_Name__c</fullName>
        <description>The field is required. It indicates the category to which the system property belongs.</description>
        <label>Category Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Key__c</fullName>
        <description>The field is required. The combination of the category and the key is used to uniquely identify the system property.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Properties</label>
</CustomObject>

classes/csaLookupkeyGeneratorInstallerRemote.cls
public with sharing class csaLookupkeyGeneratorInstallerRemote {

    public class CheckInstall extends nFORCE.RemoteActionController.Endpoint {
        public override virtual Object invoke(Map<String,Object> params) {
            nFORCE.SystemProperties properties = nFORCE.SystemProperties.getInstance();
            return properties.getPropertyAsBoolean(
                nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
                csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDKEY,
                false
            );
        }
    }

    public class Install extends nFORCE.RemoteActionController.Endpoint {
        public override virtual Object invoke(Map<String,Object> params) {
            List<sObject> toInsert = new List<sObject>();

            Id adminGroupId = [SELECT Id FROM nFORCE__Group__c WHERE nFORCE__App__c = 'admin'].Id;

            toInsert.add(nFORCE.SystemProperties.createProperty(
                nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
                csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDKEY,
                csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDVALUE,
                true
            ));

            toInsert.add(new nFORCE__Route__c(
                Name = csaLookupkeyGeneratorConstants.ROUTE_NAME,
                nFORCE__Topbar__c = nCSA_FRAME.csaConstants.TOPBAR_PAGE,
                nFORCE__Navigation__c = nCSA_FRAME.csaConstants.NAVIGATION_PAGE,
                nFORCE__Sub_Navigation__c = nCSA_FRAME.csaConstants.SUB_NAVIGATION_PAGE,
                nFORCE__Body__c = csaLookupkeyGeneratorConstants.ROUTE_BODY,
                nFORCE__App__c = csaLookupkeyGeneratorConstants.ROUTE_APP,
                nFORCE__lookupKey__c = csaLookupkeyGeneratorConstants.ROUTE_KEY
            ));

            nFORCE__Route_Group__c routeGroup = new nFORCE__Route_Group__c(
                nFORCE__Group__c = adminGroupId,
                nFORCE__Order__c = 1020,
                nFORCE__lookupKey__c = csaLookupkeyGeneratorConstants.ROUTEGROUP_KEY
            );

            routeGroup.nFORCE__Route__r = new nFORCE__Route__c(
                nFORCE__lookupKey__c = csaLookupkeyGeneratorConstants.ROUTE_KEY
            );
            routeGroup.nFORCE__Parent_Route__r = new nFORCE__Route__c(
                nFORCE__lookupKey__c = nCSA_FRAME.csaConstants.ADMINDASHBOARD_ROUTEKEY
            );

            toInsert.add(routeGroup);


            nFORCE.DMLUtility.insertObj(toInsert);
            return null;
        }
    }

    public class Uninstall extends nFORCE.RemoteActionController.Endpoint {
        public override virtual Object invoke(Map<String,Object> params) {
            List<sObject> toDelete = new List<sObject>();

            toDelete.addAll([SELECT
                                    Id
                            FROM
                                    nFORCE__System_Properties__c
                            WHERE
                                    nFORCE__Key__c = :csaLookupkeyGeneratorConstants.PROPERTY_INSTALLEDKEY
                            OR
                                    nFORCE__Category_Name__c = :csaLookupkeyGeneratorConstants.PROPERTY_CATEGORY
                            LIMIT 100]);

            toDelete.addAll([SELECT
                                    Id
                            FROM
                                    nFORCE__Route_Group__c
                            WHERE
                                    nFORCE__Route__r.nFORCE__App__c = :csaLookupkeyGeneratorConstants.ROUTE_APP
                            LIMIT 100]);

            toDelete.addAll([SELECT
                                    Id
                            FROM
                                    nFORCE__Route__c
                            WHERE
                                    nFORCE__App__c = :csaLookupkeyGeneratorConstants.ROUTE_APP
                            LIMIT 100]);

            if(!toDelete.isEmpty()) {
                nFORCE.DMLUtility.deleteObj(toDelete);
            }

            return null;
        }
    }
}